### ISSUE TITLE
Copy Constructor?

### ISSUE THREAD

**Issue by dgerangal** [Seneca-BTP500/btp500-f17#1]
My code is breaking at test 8 for part 1.
It shows me an error about if I did deep copy correctly, but my code compiles without any error (even with GDB).
Can anyone help me with copy constructor and assignment operator?

**Comment by SeanPrashad** [comment]
I'd recommend busting open the [copy/move course notes from BTP305](https://scs.senecac.on.ca/~btp305/pages/content/class.html#mov) to refresh yourself on what those two functions actually do! You might even find code that you can copy-pasta for your solution.

At a high-level, for both the **Copy Constructor** (CC) & **Copy Assignment** (CA) operators, you will need to consider the following:

- Does my object already exist?
  - If so, I will need to delete whatever data nodes are inside of it - do I need to delete sentinels?
  - If my object does not exist, I will need to setup my sentinel nodes if i'm using them!
- How will I perform a deep copy if I need to?
  - Think about using a loop to traverse each node from `rhs` (*right-hand-side*) starting from the **first data node**, creating a new node (`nn`) using `rhs.data_` in the constructor and lastly hooking up `nn.next_` and `nn.prev_` accordingly
- Should I be using the pre-written `insert` function?
  - If I use my handy-dandy `insert` function I wrote, will the run-time for the CC/CA increase/decrease? (*Think very long and hard about it and if you think it's not a problem, **THINK EVEN HARDER***)

With that being said, in pseudo-code (the english equivalent of code), maybe write what you think the **Copy Constructor** should contain @dgerangal! Others can jump on to help too.

**Comment by dgerangal** [comment]
Thanks @SeanPrashad !
