### ISSUE TITLE
Assignment 2 - a2timing.cpp missing

### ISSUE THREAD

**Issue by SeanPrashad** [Seneca-BTP500/btp500-f17#10]
Hi @bleungwpg & @cathyatseneca,

Could you please upload `a2timing.cpp` to the course repo? It's used in [Assignment 2 Part D](https://github.com/Seneca-BTP500/btp500-f17/wiki/assignment-2#part-d-5-marks).

Thank you!

**Comment by cathyatseneca** [comment]
Sorry didn't realize it was missing till too late.  Its up now Sean
