### ISSUE TITLE
Run Time Improvements Without Changing Every Function - Part B

### ISSUE THREAD

**Issue by jselmani** [Seneca-BTP500/btp500-f17#11]
Hey everyone,

I've been working on Assignment 2 (started yesterday) and have seen significant improvements to the run time of the entire test program.  The only issue I am having is that I did not make changes to every function that @cathyatseneca has asked us to do, only those that had long run times and were being called within other functions.  I have screenshots to show the difference below:

#### Before Changes
![beforechanges](https://user-images.githubusercontent.com/25250594/32623265-8eb4fad8-c553-11e7-9066-a3284dcca801.PNG)

#### After Changes
![afterchanges](https://user-images.githubusercontent.com/25250594/32623289-a44b007c-c553-11e7-9d3e-217fd39aa36f.PNG)

I just wanted to know if anyone else has run into this or saw similar results by making a few tweaks to very few functions.

Look forward to hearing your responses.

**Comment by SeanPrashad** [comment]
I and a few others experienced the same @jselmani - now you should look to refactor the respective functions so that they execute with [`O(𝑛)` run-time or better](https://github.com/Seneca-BTP500/btp500-f17/wiki/assignment-2#part-b-10-marks)!
