### ISSUE TITLE
Lab4 compile issue

### ISSUE THREAD

**Issue by mariekarimizadeh** [Seneca-BTP500/btp500-f17#2]
I'm trying to compile my lab4 code with the tester but I'm getting a weird error that I've never seen before. Even after googling I'm unsure what it means:

```c
g++ stack.h lab4.cpp lab4tester.cpp
/tmp/ccaqPa1A.o: In function `main':
lab4tester.cpp:(.text+0x156): undefined reference to `bracketCheck(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: ld returned 1 exit status
```
(Doing just  g++ lab4tester.cpp also gives me the same error as above)

I've also tried to compile just my lab4.cpp code to see if it was the issue and got this:
```c
g++ stack.h lab4.cpp
/usr/lib/gcc/i586-suse-linux/4.6/../../../crt1.o: In function `_start':
/home/abuild/rpmbuild/BUILD/glibc-2.14.1/csu/../sysdeps/i386/elf/start.S:115: undefined reference to `main'
collect2: ld returned 1 exit status
```
![lab4_errors](https://user-images.githubusercontent.com/14205445/31751432-4d59a27a-b453-11e7-86c6-b399adbae4f7.PNG)

**Comment by SeanPrashad** [comment]
Try compiling with `g++ lab4tester.cpp lab4.cpp -std=c++0x`

**Comment by mariekarimizadeh** [comment]
I'm still receiving the same error.

```c
g++ lab4tester.cpp lab4.cpp -std=c++0x
/tmp/ccSiY7pV.o: In function `main':
lab4tester.cpp:(.text+0x156): undefined reference to `bracketCheck(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: ld returned 1 exit status
```

**Comment by SeanPrashad** [comment]
To verify, your `lab4tester.cpp` should look like the following:

```
#include <string>
#include <iostream>

bool bracketCheck(const std::string& s);

int main(void){
	std::string tests[5]={
		"a(b)c[d]ef",
		"aa[bcd(efg{hij}k[lm]no)p]qrs",
		"a(b)c]d",
		"[[]",
		"aa(bb{cc)dd}ee"
	};
	bool results[5]={true,true,false,false,false};

	for(int i=0;i<5;i++){
		if(bracketCheck(tests[i])==results[i]){
			std::cout << "Test "<< i+1 << " passed" << std::endl;
		}
		else{
			std::cout << "Test "<< i+1 << " error" << std::endl;
		}
	}
	return 0;
}
```

And your `lab4.cpp` should look something like:

```
#include "stack.h"
#include <string>

bool bracketCheck(const std::string& s){
    /* TODO */
}
```

**Comment by mariekarimizadeh** [comment]
Yep! My files are like you posted. I even removed the code I wrote within my lab4.cpp and tried to compile again. Receiving the same error.

**Comment by SeanPrashad** [comment]
Can you do a `pwd` and `ls` from Matrix and post a screenshot here?

**Comment by mariekarimizadeh** [comment]
![image](https://user-images.githubusercontent.com/14205445/31752080-1c8cfbd4-b457-11e7-9845-931273e8295e.png)

**Comment by SeanPrashad** [comment]
Can you try compiling a previous lab, like lab 1 or 2? I've never seen a `.h.gch` file so maybe try removing those: `rm stack.h.gch`

**Comment by mariekarimizadeh** [comment]
![image](https://user-images.githubusercontent.com/14205445/31752355-6b55aec2-b458-11e7-906e-ea935ec30089.png)

**Comment by SeanPrashad** [comment]
Ok - next step I would try is to back up your `Stack.h` and `lab4.cpp` **locally** then delete them completely from Matrix. Pull them both from the `btp500-f17` repo to your local HDD, slap a `return true;` into `bracketCheck()` inside `lab4.cpp` and comment out the `#include Stack.h`. This ensures that your code compiles and will return `true` for every function call inside `main()`.

Put them both back onto matrix and run `g++ lab4tester.cpp lab4.cpp -std=c++0x`. If it doesn't, then something is really weird..

**Comment by mariekarimizadeh** [comment]
One issue: I do not have a way to compile c++ code at home.
But I did follow the rest of your instruction and I'm still getting the same error.

**Comment by SeanPrashad** [comment]
I'd suggest you then look into heading into school for a few hours to try creating a minimum working code base using the[ steps I listed above](https://github.com/Seneca-BTP500/btp500-f17/issues/2#issuecomment-337786947).

If that doesn't work, then maybe try dropping by the Learning Centre in the library to have someone assist with getting you up and running!

**Comment by SeanPrashad** [comment]
@mariekarimizadeh - were you able to resolve the issue?

**Comment by mariekarimizadeh** [comment]
@SeanPrashad Yes! I was able too.
The issue was me not looking at my code fully. I was so focused on the code within the functions (where I figured the issue was from) that I didnt realize I forgot to remove the "template <typename T>" from an earlier draft.
