### ISSUE TITLE
Lab4 Submission Error

### ISSUE THREAD

**Issue by RosarioAleCali** [Seneca-BTP500/btp500-f17#3]
Hello Everyone!

I am currently working on Lab 4 and I am having a small issue submitting my lab on matrix.
On VS and on matrix (when compiling manually) I get the following results:
Test 1 passed
Test 2 passed
Test 3 error
Test 4 error
Test 5 error

These results look correct to me based on the table inside of the Lab 4 Documentation.

My problem is when I use the submitter on Matrix then I get different results than the tester.
Have you guys had the same issue??

**Comment by SeanPrashad** [comment]
Hey @RosarioAleCali! The submitter program (`~catherine.leung/submit btp500-L4`) and `lab4tester.cpp` test the same 5 cases:

![Lab 4 Output](https://user-images.githubusercontent.com/13009507/31847904-401d90a2-b5f3-11e7-872c-6f7b3ea0ce40.png)

It looks like you're off by a little bit - keep going!

**Comment by RosarioAleCali** [comment]
Hey @SeanPrashad , thanks for confirming that!
I figured out what I was doing wrong.
Perhaps, I should either stop working at night or drink more Red Bull LOL

**Comment by jselmani** [comment]
LOL you kill me @RosarioAleCali
