### ISSUE TITLE
Assignment1-Move constructor

### ISSUE THREAD

**Issue by shrishtikaloha** [Seneca-BTP500/btp500-f17#6]
SortedList(SortedList&& rhs)
I am having issues with move constructor, basically it is passing the 14a test, but not the 14b which is "original and copy both refer to same list".  When running the 14b test, it throws a nullptr exception for recList.begin(). Can someone please help me?

**Comment by SeanPrashad** [comment]
@shrishtikaloha Sounds like both the front_ and back_ of each list is pointing to the same list. When one goes out of scope, the other will too (which is **NOT** what you want).

You should look to *swap* the front_ and back_ for each list like so:

1. If you're using sentinel nodes, make sure they are allocated and pointing to each other (represents an empty list)
2. Swap the front of the current object with the new list, presumably rhs's front_
3. Swap the back of the current object with the new list, presumably rhs's back_
4. Shallow copy any non-dynamic variables

Hope this helps!

**Comment by shrishtikaloha** [comment]
@SeanPrashad yeah i was able to get it done. Thank you so much.
