### ISSUE TITLE
Assignment 2 clarification

### ISSUE THREAD

**Issue by mariekarimizadeh** [Seneca-BTP500/btp500-f17#8]
I'm attempting to start a2 and had some questions. 
https://github.com/Seneca-BTP500/btp500-f17/wiki/assignment-2

**Question 1:**
Are we to implement the functions in **class Table**. Unless I missed it, it doesn't say anywhere we have to implement it? Cathy mentions 

> it describes the functionalities of a Table but does not implement any part of it

Then mentions

> The way you store it (whether you make a template struct called Record with a data member for key and value, or you store them separately in parallel structures is entirely up to you.

So it is a little bit confusing as to what we are doing with **class Table**.

**Question 1b:**
Also in the explanation of Table class Cathy mentions **int numRecords() const** and **bool isEmpty() const** but they are not in the starter file. Is it safe to assume she forgot to add them and we need to add 
   **virtual int numRecords() const;
   virtual bool isEmpty() const;**

```c
template <class TYPE>
class Table{
public:
	Table(){}
	virtual bool update(const string& key, const TYPE& value)=0;
	virtual bool remove(const string& key)=0;
	virtual bool find(const string& key, TYPE& value)=0;
	virtual ~Table(){};
};
```

**Question 2:**
Which class LPTable functions are we implementing? All? Some functions already have return values and there isn't really any explanation for the purpose of each function, other than it is a hash table.

```c
template <class TYPE>
class LPTable:public Table<TYPE>{
public:
	LPTable(int maxExpected,double percentOpen);
	LPTable(const LPTable& other);
	LPTable(LPTable&& other);
	virtual bool update(const string& key, const TYPE& value);
	virtual bool remove(const string& key);
	virtual bool find(const string& key, TYPE& value);
	virtual const LPTable& operator=(const LPTable& other);
	virtual const LPTable& operator=(LPTable&& other);
	virtual ~LPTable();
};
template <class TYPE>
LPTable<TYPE>::LPTable(int maxExpected,double percentOpen): Table<TYPE>(){
}
template <class TYPE>
LPTable<TYPE>::LPTable(const LPTable<TYPE>& other){
}
template <class TYPE>
LPTable<TYPE>::LPTable(LPTable<TYPE>&& other){
}
template <class TYPE>
bool LPTable<TYPE>::update(const string& key, const TYPE& value){
	return true;
}
template <class TYPE>
bool LPTable<TYPE>::remove(const string& key){
	return true;
}
template <class TYPE>
bool LPTable<TYPE>::find(const string& key, TYPE& value){
	return true;
}
template <class TYPE>
const LPTable<TYPE>& LPTable<TYPE>::operator=(const LPTable<TYPE>& other){
	return *this;
}
template <class TYPE>
const LPTable<TYPE>& LPTable<TYPE>::operator=(LPTable<TYPE>&& other){
	return *this;
}
template <class TYPE>
LPTable<TYPE>::~LPTable(){
}
```

**Comment by bleungwpg** [comment]
Hi I'm Ben (one of the mods).

The Table class is an abstract base class and thus does not implement any actual functionality.  It only serves as a common interface.  How each of the functions are implemented depends on the type of table it is.  Thus, you only need to implement the LPTable class as a linear probing table.

I have updated the starter files to add the isEmpty() and numRecords() into the starter file and pushed the updates.

**Comment by mariekarimizadeh** [comment]
Would you know the answer to my Question#2 by chance? If we are implementing all the functions for LPTable because some do have return values.

**Comment by SeanPrashad** [comment]
= _Disclaimer: I have not started but have made notes on the given instructions_ =

@mariekarimizadeh The functions that have `return true;` simply hold as a placeholder in the `LPTable` class. **YOU** will need to code all of the functions like `SimpleTable` except this time you'll be creating it as a `Linear Probing Table`. Cathy has thrown in those statements so your code doesn't explode with 500 errors when compiling for the previous parts.

**Comment by bleungwpg** [comment]
those functions are all stubs (functions that do not function correctly but have code as place holders). All functions need to be implemented according to spec.
