### ISSUE TITLE
Assignment #2 missing files

### ISSUE THREAD

**Issue by ithompson4** [Seneca-BTP500/btp500-f17#9]
Assignment #2 description mentions the following files: 
a2timing.cpp program, a2partb.cpp and a2partc.cpp

Where can I find these files or were they included by mistake instead of other tester or timer files?

Thank you

**Comment by SeanPrashad** [comment]
_According to the instructions:_

[Files required for Part 2B](https://github.com/Seneca-BTP500/btp500-f17/wiki/assignment-2#files-needed-for-testing)

[Files required for Part 2C](https://github.com/Seneca-BTP500/btp500-f17/wiki/assignment-2#files-needed-for-testing-1)

**Comment by ithompson4** [comment]
Sean, thank you.
